# Analise do inventario em Parquet

Notebook para ler o arquivo gerado por:

```bash
python main.py export --format parquet
```

Para analise local exploratoria, este notebook usa DuckDB como engine principal. Ele consulta Parquet direto no disco, sem precisar carregar tudo em memoria.

## Qual engine usar?

- **DuckDB**: melhor escolha inicial para explorar Parquet local, fazer SQL, agregacoes e filtros rapidamente.
- **Pandas**: bom para amostras pequenas, graficos e manipulacoes simples em memoria.
- **PySpark**: melhor quando o volume for grande demais para a maquina, quando houver muitos Parquets particionados, ou quando a analise virar pipeline distribuido.

Recomendacao para este projeto agora: **DuckDB primeiro**. Use PySpark depois se o dado crescer muito ou se voce for processar tudo em cluster.

In [15]:
from pathlib import Path

PROJECT_ROOT = Path.cwd().parent if Path.cwd().name == "notebooks" else Path.cwd()
PARQUET_PATH = PROJECT_ROOT / "exports" / "inventory.parquet"

print("Projeto:", PROJECT_ROOT)
print("Parquet:", PARQUET_PATH)
print("Existe:", PARQUET_PATH.exists())

if not PARQUET_PATH.exists():
    raise FileNotFoundError(
        f"Parquet nao encontrado: {PARQUET_PATH}. "
        "Gere o arquivo com: python main.py export --format parquet"
    )

Projeto: /Users/analuizadantas/Library/CloudStorage/OneDrive-Fiap-FaculdadedeInformáticaeAdministraçãoPaulista/Codigos/Projeto_sharepoint
Parquet: /Users/analuizadantas/Library/CloudStorage/OneDrive-Fiap-FaculdadedeInformáticaeAdministraçãoPaulista/Codigos/Projeto_sharepoint/exports/inventory.parquet
Existe: True

## Instalar dependencias, se necessario

Execute a celula abaixo somente se `import duckdb` falhar.

In [ ]:
#%pip install duckdb pandas pyarrow

Collecting duckdb
  Using cached duckdb-1.5.3-cp313-cp313-macosx_10_13_x86_64.whl.metadata (4.2 kB)
Collecting pandas
  Downloading pandas-3.0.3-cp313-cp313-macosx_10_13_x86_64.whl.metadata (79 kB)
Requirement already satisfied: pyarrow in /Users/analuizadantas/Library/CloudStorage/OneDrive-Fiap-FaculdadedeInformáticaeAdministraçãoPaulista/Codigos/Projeto_sharepoint/.venv/lib/python3.13/site-packages (18.1.0)
Collecting numpy>=1.26.0 (from pandas)
  Downloading numpy-2.4.6-cp313-cp313-macosx_14_0_x86_64.whl.metadata (6.6 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/analuizadantas/Library/CloudStorage/OneDrive-Fiap-FaculdadedeInformáticaeAdministraçãoPaulista/Codigos/Projeto_sharepoint/.venv/lib/python3.13/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /Users/analuizadantas/Library/CloudStorage/OneDrive-Fiap-FaculdadedeInformáticaeAdministraçãoPaulista/Codigos/Projeto_sharepoint/.venv/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Using cached duckdb-1.5.3-cp313-cp313-macosx_10_13_x86_64.whl (17.3 MB)
Downloading pandas-3.0.3-cp313-cp313-macosx_10_13_x86_64.whl (10.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.3/10.3 MB 14.1 MB/s  0:00:00eta 0:00:01
Downloading numpy-2.4.6-cp313-cp313-macosx_14_0_x86_64.whl (6.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.5/6.5 MB 44.9 MB/s  0:00:00
Installing collected packages: numpy, duckdb, pandas
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3/3 [pandas]2m2/3 [pandas]
Successfully installed duckdb-1.5.3 numpy-2.4.6 pandas-3.0.3
Note: you may need to restart the kernel to use updated packages.

## Abrir DuckDB e criar view sobre o Parquet

In [16]:
import duckdb

parquet_sql_path = str(PARQUET_PATH).replace("'", "''")
con = duckdb.connect(database=":memory:")
con.execute(f"CREATE OR REPLACE VIEW inventory AS SELECT * FROM read_parquet('{parquet_sql_path}')")

con.sql("DESCRIBE inventory").df()

                            column_name column_type null   key default extra
0                           tenant_site     VARCHAR  YES  None    None  None
1                             site_name     VARCHAR  YES  None    None  None
2                              site_url     VARCHAR  YES  None    None  None
3                            biblioteca     VARCHAR  YES  None    None  None
4             caminho_completo_da_pasta     VARCHAR  YES  None    None  None
5                 nome_arquivo_ou_pasta     VARCHAR  YES  None    None  None
6                             tipo_item     VARCHAR  YES  None    None  None
7                              extensao     VARCHAR  YES  None    None  None
8                             tipo_mime     VARCHAR  YES  None    None  None
9                         tamanho_bytes      BIGINT  YES  None    None  None
10                    tamanho_formatado     VARCHAR  YES  None    None  None
11                         data_criacao     VARCHAR  YES  None    None  None
12                     data_modificacao     VARCHAR  YES  None    None  None
13               data_ultimo_uso_acesso     INTEGER  YES  None    None  None
14  quantidade_arquivos_dentro_da_pasta      BIGINT  YES  None    None  None
15             volume_total_pasta_bytes      BIGINT  YES  None    None  None
16         volume_total_pasta_formatado     VARCHAR  YES  None    None  None
17                              id_item     VARCHAR  YES  None    None  None
18                             id_drive     VARCHAR  YES  None    None  None
19                       status_leitura     VARCHAR  YES  None    None  None
20                     data_hora_coleta     VARCHAR  YES  None    None  None
21                         caminho_item     VARCHAR  YES  None    None  None

## Sites presentes no Parquet

Lista todos os sites encontrados no arquivo Parquet, com contagem de bibliotecas, arquivos, pastas e volume total de arquivos.

In [17]:
sites_df = con.sql("""
SELECT
    site_name,
    site_url,
    tenant_site,
    COUNT(DISTINCT biblioteca) AS bibliotecas,
    COUNT_IF(tipo_item = 'file') AS arquivos,
    COUNT_IF(tipo_item = 'folder') AS pastas,
    SUM(CASE WHEN tipo_item = 'file' THEN tamanho_bytes ELSE 0 END) AS total_bytes_arquivos,
    ROUND(SUM(CASE WHEN tipo_item = 'file' THEN tamanho_bytes ELSE 0 END) / 1024.0 / 1024.0 / 1024.0, 2) AS total_gb_arquivos
FROM inventory
GROUP BY site_name, site_url, tenant_site
ORDER BY total_bytes_arquivos DESC NULLS LAST, site_name
""").df()

sites_df

,site_name,site_url,tenant_site,bibliotecas,arquivos,pastas,total_bytes_arquivos,total_gb_arquivos
0,Expanzio,https://expanziobr.sharepoint.com/sites/Expanzio,expanziobr.sharepoint.com,1,368317.0,141898.0,1.175054e+12,1094.35
1,Marketing,https://expanziobr.sharepoint.com/sites/Marketing,expanziobr.sharepoint.com,1,5097.0,274.0,3.105802e+11,289.25
2,Comercial,https://expanziobr.sharepoint.com/sites/Comercial,expanziobr.sharepoint.com,1,9940.0,462.0,2.137939e+10,19.91
3,Financeiro,https://expanziobr.sharepoint.com/sites/Financ...,expanziobr.sharepoint.com,1,7353.0,653.0,1.644318e+09,1.53
4,Licenciamento,https://expanziobr.sharepoint.com/sites/Licenc...,expanziobr.sharepoint.com,1,68.0,8.0,2.187074e+07,0.02
5,RH,https://expanziobr.sharepoint.com/sites/RH,expanziobr.sharepoint.com,1,51.0,18.0,1.483471e+07,0.01
6,"expanziobr-my.sharepoint.com,12b045b6-65ad-459...",https://expanziobr-my.sharepoint.com,expanziobr-my.sharepoint.com,2,240.0,3.0,8.452940e+05,0.00
7,Tenant Administration,https://expanziobr-admin.sharepoint.com,expanziobr-admin.sharepoint.com,4,1.0,5.0,2.880000e+02,0.00
8,Aplicativos,https://expanziobr.sharepoint.com/sites/appcat...,expanziobr.sharepoint.com,3,0.0,3.0,0.000000e+00,0.00
9,Comercial-Propostas Comerciais,https://expanziobr.sharepoint.com/sites/Comerc...,expanziobr.sharepoint.com,1,0.0,1.0,0.000000e+00,0.00
10,Communication site,https://expanziobr.sharepoint.com,expanziobr.sharepoint.com,1,0.0,1.0,0.000000e+00,0.00
11,Fundamental Site for SharePoint Tenants.,http://fundamental_donotdelete_ff88492a-dcf0-4...,fundamental_donotdelete_ff88492a-dcf0-4ea9-aa7...,1,0.0,1.0,0.000000e+00,0.00
12,Gerente de Contas,https://expanziobr.sharepoint.com/sites/Gerent...,expanziobr.sharepoint.com,1,0.0,3.0,0.000000e+00,0.00
13,Intranet teste,https://expanziobr.sharepoint.com/sites/Intran...,expanziobr.sharepoint.com,1,0.0,1.0,0.000000e+00,0.00
14,Liderança,https://expanziobr.sharepoint.com/sites/Liderana,expanziobr.sharepoint.com,1,0.0,2.0,0.000000e+00,0.00
15,Team Site,https://expanziobr.sharepoint.com/sites/conten...,expanziobr.sharepoint.com,1,0.0,1.0,0.000000e+00,0.00
16,Técnico,https://expanziobr.sharepoint.com/sites/msteam...,expanziobr.sharepoint.com,1,0.0,2.0,0.000000e+00,0.00

## Contagens e qualidade basica

In [11]:
con.sql("""
SELECT
    COUNT(*) AS total_linhas,
    COUNT_IF(tipo_item = 'file') AS arquivos,
    COUNT_IF(tipo_item = 'folder') AS pastas,
    COUNT(DISTINCT site_url) AS sites,
    COUNT(DISTINCT id_drive) AS drives,
    COUNT(DISTINCT biblioteca) AS bibliotecas,
    SUM(CASE WHEN tipo_item = 'file' THEN tamanho_bytes ELSE 0 END) AS total_bytes_arquivos,
    MIN(data_modificacao) AS menor_data_modificacao,
    MAX(data_modificacao) AS maior_data_modificacao
FROM inventory
""").df()

,total_linhas,arquivos,pastas,sites,drives,bibliotecas,total_bytes_arquivos,menor_data_modificacao,maior_data_modificacao
0,520617,378257.0,142360.0,2,2,1,1.196433e+12,1983-11-17T03:55:42Z,2026-06-04T03:31:20Z

In [12]:
con.sql("""
SELECT
    tipo_item,
    status_leitura,
    COUNT(*) AS quantidade
FROM inventory
GROUP BY tipo_item, status_leitura
ORDER BY tipo_item, status_leitura
""").df()

  tipo_item status_leitura  quantidade
0      file             ok      378257
1    folder             ok      142360

## Amostra dos metadados

In [13]:
con.sql("""
SELECT
    site_name,
    biblioteca,
    caminho_item,
    nome_arquivo_ou_pasta,
    tipo_item,
    extensao,
    tipo_mime,
    tamanho_bytes,
    data_criacao,
    data_modificacao,
    data_ultimo_uso_acesso,
    caminho_completo_da_pasta
FROM inventory
WHERE tipo_item = 'file'
ORDER BY data_modificacao DESC NULLS LAST
LIMIT 30
""").df()

,site_name,biblioteca,caminho_item,nome_arquivo_ou_pasta,tipo_item,extensao,tipo_mime,tamanho_bytes,data_criacao,data_modificacao,data_ultimo_uso_acesso,caminho_completo_da_pasta
0,Expanzio,Documents,Documents/General/1. Corporativos/GRUPO BOTICÁ...,LJ SHOP. METRÔ BOULEVARD - BOT. - LEV. ARQ. - ...,file,pdf,application/pdf,506905,2026-06-04T03:30:46Z,2026-06-04T03:30:46Z,<NA>,Documents/General/1. Corporativos/GRUPO BOTICÁ...
1,Expanzio,Documents,Documents/General/1. Corporativos/GRUPO BOTICÁ...,LJ SHOP. METRÔ BOULEVARD - BOT. - LEV. ARQ. - ...,file,pdf,application/pdf,509081,2026-06-04T03:30:46Z,2026-06-04T03:30:46Z,<NA>,Documents/General/1. Corporativos/GRUPO BOTICÁ...
2,Expanzio,Documents,Documents/General/1. Corporativos/GRUPO BOTICÁ...,LJ SHOP. METRÔ BOULEVARD - BOT. - LEV. ARQ. - ...,file,pdf,application/pdf,509691,2026-06-04T03:30:46Z,2026-06-04T03:30:46Z,<NA>,Documents/General/1. Corporativos/GRUPO BOTICÁ...
3,Expanzio,Documents,Documents/General/1. Corporativos/GRUPO BOTICÁ...,LJ SHOP. METRÔ BOULEVARD - BOT. - LEV. ARQ. - ...,file,pdf,application/pdf,499966,2026-06-04T03:30:46Z,2026-06-04T03:30:46Z,<NA>,Documents/General/1. Corporativos/GRUPO BOTICÁ...
4,Expanzio,Documents,Documents/General/1. Corporativos/GRUPO BOTICÁ...,LJ SHOP. METRÔ BOULEVARD - BOT. - LEV. ARQ.- R...,file,dwg,application/octet-stream,16136189,2026-06-04T03:30:34Z,2026-06-04T03:30:34Z,<NA>,Documents/General/1. Corporativos/GRUPO BOTICÁ...
5,Expanzio,Documents,Documents/General/1. Corporativos/SMART FIT/RN...,SBRRNISGA02-EXE-INC-000-PROJ-R02.dwl,file,dwl,application/octet-stream,68,2026-06-03T23:12:15Z,2026-06-03T23:12:07Z,<NA>,Documents/General/1. Corporativos/SMART FIT/RN...
6,Expanzio,Documents,Documents/General/1. Corporativos/SMART FIT/RN...,SBRRNISGA02-EXE-INC-000-PROJ-R02.dwl2,file,dwl2,application/octet-stream,218,2026-06-03T23:12:15Z,2026-06-03T23:12:07Z,<NA>,Documents/General/1. Corporativos/SMART FIT/RN...
7,Expanzio,Documents,Documents/General/1. Corporativos/BRADESCO/SP/...,AV PAULISTA BELA VISTA-BRADESCO-EVTL-R00.pdf,file,pdf,application/pdf,13943379,2026-06-03T22:10:04Z,2026-06-03T22:10:04Z,<NA>,Documents/General/1. Corporativos/BRADESCO/SP/...
8,Expanzio,Documents,Documents/General/1. Corporativos/BACCARAT BRA...,BACCARAT-PROJ-INC-R00-002.pdf,file,pdf,application/pdf,279023,2026-06-03T21:15:04Z,2026-06-03T21:18:10Z,<NA>,Documents/General/1. Corporativos/BACCARAT BRA...
9,Expanzio,Documents,Documents/General/1. Corporativos/BACCARAT BRA...,BACCARAT-PROJ-INC-R00-001.pdf,file,pdf,application/pdf,335186,2026-06-03T21:15:06Z,2026-06-03T21:17:45Z,<NA>,Documents/General/1. Corporativos/BACCARAT BRA...
10,Expanzio,Documents,Documents/General/1. Corporativos/BACCARAT BRA...,BACCARAT-PROJ-INC-R00.dwg,file,dwg,application/octet-stream,998718,2026-06-03T20:32:24Z,2026-06-03T21:16:55Z,<NA>,Documents/General/1. Corporativos/BACCARAT BRA...
11,Expanzio,Documents,Documents/General/1. Corporativos/BACCARAT BRA...,BACCARAT-PROJ-INC-R00.bak,file,bak,application/octet-stream,1001123,2026-06-03T20:50:32Z,2026-06-03T21:16:13Z,<NA>,Documents/General/1. Corporativos/BACCARAT BRA...
12,Expanzio,Documents,Documents/General/1. Corporativos/BACCARAT BRA...,BACCARAT-MEMORIAL DESCRITIVO-INC-R00.pdf,file,pdf,application/pdf,247827,2026-06-03T21:07:51Z,2026-06-03T21:12:34Z,<NA>,Documents/General/1. Corporativos/BACCARAT BRA...
13,Expanzio,Documents,Documents/General/1. Corporativos/BACCARAT BRA...,BACCARAT-MEMORIAL DESCRITIVO-INC-R00.docx,file,docx,application/vnd.openxmlformats-officedocument....,203379,2026-06-03T20:53:25Z,2026-06-03T21:11:51Z,<NA>,Documents/General/1. Corporativos/BACCARAT BRA...
14,Expanzio,Documents,Documents/General/1. Corporativos/SESI SENAI/S...,SN 163 COMPROVANTE ATENDIMENTO RECURSO 03.06.2...,file,pdf,application/pdf,229425,2026-06-03T21:04:22Z,2026-06-03T21:05:16Z,<NA>,Documents/General/1. Corporativos/SESI SENAI/S...
15,Expanzio,Documents,Documents/General/1. Corporativos/GRUPO BOTICÁ...,LJ - Cidade Mãe do Céu.zip,file,zip,application/zip,3833442,2026-06-03T21:05:21Z,2026-06-03T21:05:06Z,<NA>,Documents/General/1. Corporativos/GRUPO BOTICÁ...
16,Expanzio,Documents,Documents/General/1. Corporativos/SESI SENAI/S...,SN.163 - RRT PROJETO.pdf,file,pdf,application/pdf,234609,2026-06-03T21:04:01Z,2026-06-03T21:04:01Z,<NA>,Documents/General/1. Corporativos/SESI SENAI/S...
17,Expanzio,Documents,Documents/General/1. Corporativos/SESI SENAI/S...,SN.163 - PROJ. ACESS.- APROVAÇÃO_FL02.pdf,file,pdf,application/pdf,936749,2026-06-03T20:59:51Z,2026-06-03T20:59:51Z,<NA>,Documents/General/1. Corporativos/SESI SENAI/S...
18,Expanzio,Documents,Documents/General/1. Corporativos/SESI SENAI/S...,SN.163 - PROJ. ACESS.- APROVAÇÃO FL02.dwf,file,dwf,application/octet-stream,616376,2026-06-03T20:59:50Z,2026-06-03T20:59:50Z,<NA>,Documents/General/1. Corporativos/SESI SENAI/S...
19,Expanzio,Documents,Documents/General/1. Corporativos/SMART FIT/DF...,PSCIP_00.dwg,file,dwg,application/octet-stream,20722847,2026-06-03T16:49:55Z,2026-06-03T20:58:26Z,<NA>,Documents/General/1. Corporativos/SMART FIT/DF...
20,Expanzio,Documents,Documents/General/1. Corporativos/GRUPO BOTICÁ...,30.png,file,png,image/png,843572,2026-06-03T20:50:25Z,2026-06-03T20:50:25Z,<NA>,Documents/General/1. Corporativos/GRUPO BOTICÁ...
21,Expanzio,Documents,Documents/General/1. Corporativos/GRUPO BOTICÁ...,32.png,file,png,image/png,363316,2026-06-03T20:50:25Z,2026-06-03T20:50:25Z,<NA>,Documents/General/1. Corporativos/GRUPO BOTICÁ...
22,Expanzio,Documents,Documents/General/1. Corporativos/GRUPO BOTICÁ...,31.png,file,png,image/png,604086,2026-06-03T20:50:25Z,2026-06-03T20:50:25Z,<NA>,Documents/General/1. Corporativos/GRUPO BOTICÁ...
23,Expanzio,Documents,Documents/General/1. Corporativos/GRUPO BOTICÁ...,27.png,file,png,image/png,732351,2026-06-03T20:50:25Z,2026-06-03T20:50:25Z,<NA>,Documents/General/1. Corporativos/GRUPO BOTICÁ...
24,Expanzio,Documents,Documents/General/1. Corporativos/GRUPO BOTICÁ...,29.png,file,png,image/png,665005,2026-06-03T20:50:24Z,2026-06-03T20:50:24Z,<NA>,Documents/General/1. Corporativos/GRUPO BOTICÁ...
25,Expanzio,Documents,Documents/General/1. Corporativos/GRUPO BOTICÁ...,28.png,file,png,image/png,769374,2026-06-03T20:50:24Z,2026-06-03T20:50:24Z,<NA>,Documents/General/1. Corporativos/GRUPO BOTICÁ...
26,Expanzio,Documents,Documents/General/1. Corporativos/GRUPO BOTICÁ...,26.png,file,png,image/png,725873,2026-06-03T20:50:24Z,2026-06-03T20:50:24Z,<NA>,Documents/General/1. Corporativos/GRUPO BOTICÁ...
27,Expanzio,Documents,Documents/General/1. Corporativos/GRUPO BOTICÁ...,25.png,file,png,image/png,713138,2026-06-03T20:50:24Z,2026-06-03T20:50:24Z,<NA>,Documents/General/1. Corporativos/GRUPO BOTICÁ...
28,Expanzio,Documents,Documents/General/1. Corporativos/GRUPO BOTICÁ...,21.png,file,png,image/png,474488,2026-06-03T20:50:24Z,2026-06-03T20:50:24Z,<NA>,Documents/General/1. Corporativos/GRUPO BOTICÁ...
29,Expanzio,Documents,Documents/General/1. Corporativos/GRUPO BOTICÁ...,23.png,file,png,image/png,458635,2026-06-03T20:50:23Z,2026-06-03T20:50:23Z,<NA>,Documents/General/1. Corporativos/GRUPO BOTICÁ...

## Extensoes mais comuns

In [14]:
con.sql("""
SELECT
    COALESCE(NULLIF(extensao, ''), '(sem extensao)') AS extensao,
    COUNT(*) AS arquivos,
    SUM(tamanho_bytes) AS total_bytes,
    ROUND(SUM(tamanho_bytes) / 1024.0 / 1024.0 / 1024.0, 2) AS total_gb
FROM inventory
WHERE tipo_item = 'file'
GROUP BY 1
ORDER BY arquivos DESC
LIMIT 50
""").df()

          extensao  arquivos   total_bytes  total_gb
0              pdf    170157  2.188267e+11    203.80
1              dwg     76742  2.094132e+11    195.03
2              jpg     50875  1.055206e+11     98.27
3             jpeg     17488  7.081516e+09      6.60
4             docx     11640  2.051431e+10     19.11
5              bak      7192  9.081917e+10     84.58
6              zip      6071  1.972960e+11    183.75
7              png      5880  8.542722e+09      7.96
8              rfa      4464  2.975651e+09      2.77
9             xlsx      3158  8.195596e+08      0.76
10             log      3017  7.919643e+06      0.01
11             doc      2499  1.893945e+09      1.76
12             pat      2145  4.735332e+06      0.00
13             dwl      1662  1.159430e+05      0.00
14            dwl2      1658  3.651170e+05      0.00
15            heic      1272  2.041259e+09      1.90
16             dwf      1232  4.075979e+09      3.80
17             mp4      1054  1.200794e+11    111.83
18             sld       734  8.558670e+05      0.00
19             dxf       728  3.217661e+09      3.00
20             msg       652  8.074993e+08      0.75
21             rar       559  3.971958e+10     36.99
22             dat       552  1.174061e+08      0.11
23             xls       412  7.942806e+07      0.07
24        download       375  2.284304e+07      0.02
25             lsp       354  1.813624e+06      0.00
26             txt       351  5.085983e+06      0.00
27             mov       347  1.740645e+10     16.21
28             rvt       337  2.553520e+10     23.78
29             rws       333  2.120726e+08      0.20
30             rpc       282  8.686427e+08      0.81
31  (sem extensao)       273  5.533547e+08      0.52
32            html       266  1.621981e+08      0.15
33             csv       257  9.281000e+04      0.00
34             bmp       244  1.790078e+08      0.17
35             skp       195  1.360466e+10     12.67
36             tmp       177  3.544652e+09      3.30
37             ctb       158  7.232440e+05      0.00
38            pptx       150  1.966703e+09      1.83
39             err       135  3.431500e+04      0.00
40             rte       132  1.591464e+10     14.82
41             pfx       124  1.161980e+06      0.00
42             tif       122  1.018691e+09      0.95
43             mnu       110  1.041497e+07      0.01
44            jfif       109  2.422539e+07      0.02
45             skb        88  5.710062e+09      5.32
46             ifc        87  5.291415e+09      4.93
47            xlsm        80  2.949195e+08      0.27
48             css        74  3.596238e+06      0.00
49             dyn        52  6.387322e+06      0.01

## Bibliotecas por volume

In [12]:
con.sql("""
SELECT
    site_name,
    site_url,
    biblioteca,
    COUNT(*) AS arquivos,
    SUM(tamanho_bytes) AS total_bytes,
    ROUND(SUM(tamanho_bytes) / 1024.0 / 1024.0 / 1024.0, 2) AS total_gb
FROM inventory
WHERE tipo_item = 'file'
GROUP BY site_name, site_url, biblioteca
ORDER BY total_bytes DESC
LIMIT 50
""").df()

,site_name,site_url,biblioteca,arquivos,total_bytes,total_gb
0,Comercial,https://expanziobr.sharepoint.com/sites/Comercial,Documents,9940,2.137939e+10,19.91

## Pastas por volume calculado

In [13]:
con.sql("""
SELECT
    site_name,
    site_url,
    biblioteca,
    caminho_item AS pasta,
    quantidade_arquivos_dentro_da_pasta AS arquivos_na_pasta,
    volume_total_pasta_bytes,
    ROUND(volume_total_pasta_bytes / 1024.0 / 1024.0 / 1024.0, 2) AS total_gb,
    data_modificacao
FROM inventory
WHERE tipo_item = 'folder'
ORDER BY volume_total_pasta_bytes DESC NULLS LAST
LIMIT 50
""").df()

,site_name,site_url,biblioteca,pasta,arquivos_na_pasta,volume_total_pasta_bytes,total_gb,data_modificacao
0,Comercial,https://expanziobr.sharepoint.com/sites/Comercial,Documents,root/General,9940,21379385513,19.91,2025-07-19T09:30:57Z
1,Comercial,https://expanziobr.sharepoint.com/sites/Comercial,Documents,root,9940,21379385513,19.91,2026-06-01T18:05:02Z
2,Comercial,https://expanziobr.sharepoint.com/sites/Comercial,Documents,root/General/Pastas q não pertecem ao comercial,801,9152667801,8.52,2025-10-11T13:21:46Z
3,Comercial,https://expanziobr.sharepoint.com/sites/Comercial,Documents,root/General/Pastas q não pertecem ao comercia...,33,8322764687,7.75,2025-10-11T13:45:20Z
4,Comercial,https://expanziobr.sharepoint.com/sites/Comercial,Documents,root/General/Pastas q não pertecem ao comercia...,25,8322251027,7.75,2025-07-07T20:24:47Z
5,Comercial,https://expanziobr.sharepoint.com/sites/Comercial,Documents,root/General/Pastas q não pertecem ao comercia...,7,8311518815,7.74,2025-11-27T19:56:38Z
6,Comercial,https://expanziobr.sharepoint.com/sites/Comercial,Documents,"root/General/Apresentações Comerciais, Meet e ...",60,6544691565,6.10,2024-10-01T18:12:33Z
7,Comercial,https://expanziobr.sharepoint.com/sites/Comercial,Documents,"root/General/Apresentações Comerciais, Meet e ...",7,3361998692,3.13,2023-03-21T15:18:16Z
8,Comercial,https://expanziobr.sharepoint.com/sites/Comercial,Documents,"root/General/Apresentações Comerciais, Meet e ...",2,2949184913,2.75,2023-04-05T15:33:26Z
9,Comercial,https://expanziobr.sharepoint.com/sites/Comercial,Documents,root/General/1. Operações e Desenvolvimento Co...,317,1973079346,1.84,2025-10-25T22:15:56Z
10,Comercial,https://expanziobr.sharepoint.com/sites/Comercial,Documents,root/General/1. Operações e Desenvolvimento Co...,304,1942343923,1.81,2025-10-25T22:18:48Z
11,Comercial,https://expanziobr.sharepoint.com/sites/Comercial,Documents,root/General/3. Pré Vendas e Vendas,8138,1938747111,1.81,2025-10-25T22:25:16Z
12,Comercial,https://expanziobr.sharepoint.com/sites/Comercial,Documents,root/General/3. Pré Vendas e Vendas/3.1 Propos...,7678,1565399818,1.46,2025-10-25T22:26:39Z
13,Comercial,https://expanziobr.sharepoint.com/sites/Comercial,Documents,"root/General/Apresentações Comerciais, Meet e ...",2,1267544234,1.18,2024-10-10T19:27:46Z
14,Comercial,https://expanziobr.sharepoint.com/sites/Comercial,Documents,root/General/Playbook Provisório,76,901848671,0.84,2025-10-13T19:31:30Z
15,Comercial,https://expanziobr.sharepoint.com/sites/Comercial,Documents,root/General/Playbook Provisório/8.ENABLEMENT ...,19,534906865,0.50,2023-08-21T16:47:30Z
16,Comercial,https://expanziobr.sharepoint.com/sites/Comercial,Documents,root/General/Playbook Provisório/8.ENABLEMENT ...,4,523548431,0.49,2023-08-21T16:47:32Z
17,Comercial,https://expanziobr.sharepoint.com/sites/Comercial,Documents,"root/General/Apresentações Comerciais, Meet e ...",3,490173969,0.46,2023-03-21T18:53:43Z
18,Comercial,https://expanziobr.sharepoint.com/sites/Comercial,Documents,root/General/2. Materiais de Apoio Comercial,20,363178631,0.34,2025-10-25T22:19:50Z
19,Comercial,https://expanziobr.sharepoint.com/sites/Comercial,Documents,root/General/Pastas q não pertecem ao comercia...,20,344906049,0.32,2022-04-05T20:23:19Z
20,Comercial,https://expanziobr.sharepoint.com/sites/Comercial,Documents,root/General/Pastas q não pertecem ao comercia...,20,344906049,0.32,2022-04-05T20:26:04Z
21,Comercial,https://expanziobr.sharepoint.com/sites/Comercial,Documents,root/General/Pastas q não pertecem ao comercia...,20,344906049,0.32,2025-10-11T13:41:09Z
22,Comercial,https://expanziobr.sharepoint.com/sites/Comercial,Documents,root/General/3. Pré Vendas e Vendas/3.1 Propos...,534,312122501,0.29,2025-10-26T11:46:37Z
23,Comercial,https://expanziobr.sharepoint.com/sites/Comercial,Documents,root/General/Pastas q não pertecem ao comercia...,10,303990945,0.28,2025-10-11T13:41:10Z
24,Comercial,https://expanziobr.sharepoint.com/sites/Comercial,Documents,root/General/3. Pré Vendas e Vendas/3.1 Propos...,1165,283966800,0.26,2025-10-26T11:46:36Z
25,Comercial,https://expanziobr.sharepoint.com/sites/Comercial,Documents,root/General/1. Operações e Desenvolvimento Co...,158,275182567,0.26,2026-04-22T17:53:24Z
26,Comercial,https://expanziobr.sharepoint.com/sites/Comercial,Documents,root/General/7. Credenciamento LPU-BID-RFQ,404,268107105,0.25,2025-04-08T21:57:09Z
27,Comercial,https://expanziobr.sharepoint.com/sites/Comercial,Documents,root/General/3. Pré Vendas e Vendas/3.1 Propos...,779,230315824,0.21,2025-10-26T11:46:37Z
28,Comercial,https://expanziobr.sharepoint.com/sites/Comercial,Documents,root/General/3. Pré Vendas e Vendas/3.1 Propos...,760,212373341,0.20,2025-10-26T11:46:39Z
29,Comercial,https://expanziobr.sharepoint.com/sites/Comercial,Documents,root/General/3. Pré Vendas e Vendas/3.2 Contra...,423,197665243,0.18,2025-10-25T22:26:54Z
30,Comercial,https://expanziobr.sharepoint.com/sites/Comercial,Documents,"root/General/Apresentações Comerciais, Meet e ...",47,184870147,0.17,2023-05-24T18:38:57Z
31,Comercial,https://expanziobr.sharepoint.com/sites/Comercial,Documents,"root/General/Apresentações Comerciais, Meet e ...",47,184870147,0.17,2025-05-28T18:17:07Z
32,Comercial,https://expanziobr.sharepoint.com/sites/Comercial,Documents,root/General/Pastas q não pertecem ao comercia...,707,178273409,0.17,2025-10-11T13:40:26Z
33,Comercial,https://expanziobr.sharepoint.com/sites/Comercial,Documents,root/General/3. Pré Vendas e Vendas/3.6 Outbou...,37,175682050,0.16,2026-01-07T12:44:24Z
34,Comercial,https://expanziobr.sharepoint.com/sites/Comercial,Documents,root/General/3. Pré Vendas e Vendas/3.6 Outbou...,6,165191702,0.15,2026-01-15T19:40:08Z
35,Comercial,https://expanziobr.sharepoint.com/sites/Comercial,Documents,root/General/1. Operações e Desenvolvimento Co...,91,157746556,0.15,2026-04-22T17:53:23Z
36,Comercial,https://expanziobr.sharepoint.com/sites/Comercial,Documents,root/General/Pastas q não pertecem ao comercia...,573,143079342,0.13,2023-01-12T14:28:15Z
37,Comercial,https://expanziobr.sharepoint.com/sites/Comercial,Documents,root/General/3. Pré Vendas e Vendas/3.1 Propos...,393,142122063,0.13,2025-10-26T11:46:38Z
38,Comercial,https://expanziobr.sharepoint.com/sites/Comercial,Documents,root/General/3. Pré Vendas e Vendas/3.1 Propos...,3215,131479631,0.12,2025-10-26T11:46:38Z
39,Comercial,https://expanziobr.sharepoint.com/sites/Comercial,Documents,root/General/3. Pré Vendas e Vendas/3.1 Propos...,583,117700393,0.11,2025-10-26T11:46:38Z
40,Comercial,https://expanziobr.sharepoint.com/sites/Comercial,Documents,root/General/3. Pré Vendas e Vendas/3.1 Propos...,188,117065371,0.11,2025-10-26T11:46:36Z
41,Comercial,https://expanziobr.sharepoint.com/sites/Comercial,Documents,root/General/3. Pré Vendas e Vendas/3.6 Outbou...,2,108737119,0.10,2026-01-28T13:42:28Z
42,Comercial,https://expanziobr.sharepoint.com/sites/Comercial,Documents,root/General/2. Materiais de Apoio Comercial/2...,5,106245533,0.10,2025-10-25T22:20:06Z
43,Comercial,https://expanziobr.sharepoint.com/sites/Comercial,Documents,root/General/1. Operações e Desenvolvimento Co...,83,99816008,0.09,2020-04-19T23:29:34Z
44,Comercial,https://expanziobr.sharepoint.com/sites/Comercial,Documents,root/General/Reuniões Gravadas/Clientes/Caio C...,1,94591959,0.09,2026-03-27T14:19:47Z
45,Comercial,https://expanziobr.sharepoint.com/sites/Comercial,Documents,root/General/Reuniões Gravadas,1,94591959,0.09,2026-03-27T14:19:27Z
46,Comercial,https://expanziobr.sharepoint.com/sites/Comercial,Documents,root/General/Reuniões Gravadas/Clientes,1,94591959,0.09,2026-03-27T14:19:37Z
47,Comercial,https://expanziobr.sharepoint.com/sites/Comercial,Documents,root/General/Reuniões Gravadas/Clientes/Caio C...,1,94591959,0.09,2026-03-27T14:19:53Z
48,Comercial,https://expanziobr.sharepoint.com/sites/Comercial,Documents,root/General/8. Imoveis,65,94116064,0.09,2022-08-27T17:44:08Z
49,Comercial,https://expanziobr.sharepoint.com/sites/Comercial,Documents,root/General/1. Operações e Desenvolvimento Co...,72,92986636,0.09,2026-02-07T10:21:33Z

## Arquivos antigos ou sem ultimo acesso

In [14]:
con.sql("""
SELECT
    COUNT(*) AS arquivos,
    COUNT_IF(data_ultimo_uso_acesso IS NULL OR data_ultimo_uso_acesso = '') AS sem_ultimo_acesso,
    COUNT_IF(data_modificacao IS NULL OR data_modificacao = '') AS sem_data_modificacao,
    MIN(data_modificacao) AS menor_data_modificacao,
    MAX(data_modificacao) AS maior_data_modificacao
FROM inventory
WHERE tipo_item = 'file'
""").df()

,arquivos,sem_ultimo_acesso,sem_data_modificacao,menor_data_modificacao,maior_data_modificacao
0,9940,9940.0,0.0,2017-02-23T11:39:56Z,2026-06-01T18:05:02Z

## Opcional: usar Pandas em uma amostra

Use Pandas para graficos ou ajustes pequenos depois de filtrar/agregar com DuckDB.

In [15]:
sample_df = con.sql("""
SELECT *
FROM inventory
WHERE tipo_item = 'file'
ORDER BY data_modificacao DESC NULLS LAST
LIMIT 1000
""").df()

sample_df.head()

,tenant_site,site_name,site_url,biblioteca,caminho_completo_da_pasta,nome_arquivo_ou_pasta,tipo_item,extensao,tipo_mime,tamanho_bytes,...,data_modificacao,data_ultimo_uso_acesso,quantidade_arquivos_dentro_da_pasta,volume_total_pasta_bytes,volume_total_pasta_formatado,id_item,id_drive,status_leitura,data_hora_coleta,caminho_item
0,expanziobr.sharepoint.com,Comercial,https://expanziobr.sharepoint.com/sites/Comercial,Documents,root/General/9. Nossa LPU,LPU EXPANZIO_V3 (1).xlsx,file,xlsx,application/vnd.openxmlformats-officedocument....,192578,...,2026-06-01T18:05:02Z,<NA>,0,0,None,01NA37BFRGZCNY7EDCYJYJYVZZQZASPW26,b!FIB3Z0KRfU6tyPRnX3MFBomAIQiIsJtIhXnCtudAYp8r...,ok,2026-06-03T19:39:42+00:00,root/General/9. Nossa LPU/LPU EXPANZIO_V3 (1)....
1,expanziobr.sharepoint.com,Comercial,https://expanziobr.sharepoint.com/sites/Comercial,Documents,root/General/7. Credenciamento LPU-BID-RFQ,LPU_Mercado Livte.xlsx,file,xlsx,application/vnd.openxmlformats-officedocument....,219004,...,2026-05-22T12:58:20Z,<NA>,0,0,None,01NA37BFQNSPXXKLNPUFHI6CY45G7T4DKF,b!FIB3Z0KRfU6tyPRnX3MFBomAIQiIsJtIhXnCtudAYp8r...,ok,2026-06-03T19:39:42+00:00,root/General/7. Credenciamento LPU-BID-RFQ/LPU...
2,expanziobr.sharepoint.com,Comercial,https://expanziobr.sharepoint.com/sites/Comercial,Documents,root/General/Pastas q não pertecem ao comercia...,Análise_de_Maturidade_do_colaborador(a) - Isab...,file,xlsx,application/vnd.openxmlformats-officedocument....,66805,...,2026-05-15T19:50:52Z,<NA>,0,0,None,01NA37BFVG7KUJLXLMW532QV4ELIGYTAN5,b!FIB3Z0KRfU6tyPRnX3MFBomAIQiIsJtIhXnCtudAYp8r...,ok,2026-06-03T19:39:56+00:00,root/General/Pastas q não pertecem ao comercia...
3,expanziobr.sharepoint.com,Comercial,https://expanziobr.sharepoint.com/sites/Comercial,Documents,root/General/Pastas q não pertecem ao comercia...,Planilha de Avaliação de Desempenho Tradiciona...,file,xlsx,application/vnd.openxmlformats-officedocument....,45684,...,2026-05-15T19:49:51Z,<NA>,0,0,None,01NA37BFXU6RIZC6V66B42J3HKWGFSDZPE,b!FIB3Z0KRfU6tyPRnX3MFBomAIQiIsJtIhXnCtudAYp8r...,ok,2026-06-03T19:39:56+00:00,root/General/Pastas q não pertecem ao comercia...
4,expanziobr.sharepoint.com,Comercial,https://expanziobr.sharepoint.com/sites/Comercial,Documents,root/General/Pastas q não pertecem ao comercia...,Ficha de Acompanhamento de Feedback.xlsx,file,xlsx,application/vnd.openxmlformats-officedocument....,17362,...,2026-05-15T19:49:27Z,<NA>,0,0,None,01NA37BFQJ7O7TRHX2YJ5YBZE7RCBBPGZJ,b!FIB3Z0KRfU6tyPRnX3MFBomAIQiIsJtIhXnCtudAYp8r...,ok,2026-06-03T19:39:56+00:00,root/General/Pastas q não pertecem ao comercia...

## Opcional: ler o mesmo Parquet com PySpark

Use esta parte apenas se voce quiser comparar com Spark ou se o volume crescer bastante.

In [ ]:
# from pyspark.sql import SparkSession, functions as F
#
# spark = (
#     SparkSession.builder
#     .appName("analyze-sharepoint-inventory-parquet")
#     .master("local[*]")
#     .getOrCreate()
# )
#
# spark_df = spark.read.parquet(str(PARQUET_PATH))
# spark_df.printSchema()
# spark_df.show(20, truncate=80)